
/*
5.	Given a table “users” with columns “Id” (identity integer primary key) and “Name” (varchar):
a.	Write a SQL stored procedure that inserts a new record into the table and returns the value of the identity column "Id" generated by the insert statement, regardless of query scope, connection, triggers, concurrent executions, etc. 
*/


/*
CREATE TABLE `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
*/


-- Create Stored Procedure Inserting into User Table
-- Will return the new Primary Key
CREATE DEFINER=`root`@`localhost` PROCEDURE `usp_user_add`(p_name VARCHAR(50))
BEGIN
	-- Create 1 Row in User Table
	INSERT INTO users (name) VALUES (p_name);
  --  SELECT SCOPE_INDENTITY(); -- MS SQL Server.
  -- Get ID Generated
	SELECT last_insert_id();  -- MySQL
END